config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'terms/index'

  resources :rooms
  root 'home#index'
end

app/models/room.rb
class Room < ActiveRecord::Base
    has_attached_file :image, styles: { large: "650x410", medium: "250x170>", thumb: "50x50>"  }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:image, :name, :description, :price, :size, :checkin, :checkout, :adults, :kids, :size, :beds, :accomodates)
    end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/footer' %>
  </div>
</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for @room, url: rooms_path, html: { multipart: true } do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :checkin %><br>
    <%= f.date_select :checkin %>
  </div>
  <div class="field">
    <%= f.label :checkout %><br>
    <%= f.date_select :checkout %>
  </div>
  <div class="field">
    <%= f.label :adults %><br>
    <%= f.number_field :adults %>
  </div>
  <div class="field">
    <%= f.label :kids %><br>
    <%= f.number_field :kids %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :beds %><br>
    <%= f.text_field :beds %>
  </div>
  <div class="field">
    <%= f.label :accomodates %><br>
    <%= f.text_field :accomodates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Room', new_room_path %>
<h1>Our Rooms</h1>

<table>
  <thead>
    <tr>
      <th>image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Size</th>
      <th>Beds</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to (image_tag room.image.url(:medium)), room %></td>
        <td><%= link_to room.name, room %></td>
        <td><%= truncate(room.description, :length => 60) %></td>
        <td><%= room.price %></td>
        <td><%= room.size %></td>
        <td><%= room.beds %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="room">
    <div class="col-lg-3">
      <div class="room-img">
        <img src="https://www.amoils.com/health-blog/wp-content/uploads/2015/01/blog-image-bedding-dollar-paid.jpg">
      </div>
    </div>
    <div class="col-lg-6">
      <div class="room-detail">
        <h2 class="room-title">Junior Suite</h2>
        <p class="room-description">
          Our Junior Suites offer breathtaking views of the city skyline.
        </p>
        <ul class="room-size-bee">
          <li> Size: 280 sq ft </li>
          <li> Beds: 1 King(s) </li>
        </ul>
        <div class="room-amenities">
          <ul>
            <li><a href=""><i class="">a</i></a></li>
            <li><a href=""><i class="">a</i></a></li>
            <li><a href=""><i class="">a</i></a></li>
            <li><a href=""><i class="">a</i></a></li>
            <li><a href=""><i class="">a</i></a></li>
            <li><a href=""><i class="">a</i></a></li>
            <li><a href=""><i class="">a</i></a></li>
            <li><a href=""><i class="">a</i></a></li>
            <li><a href=""><i class="">a</i></a></li>
            <li><a href=""><i class="">a</i></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
       <div class="pricing text-center">
         <h1><span>From</span><br>$350</h1>
         <a class="btn btn-default" href="/">
           More Info
         </a>
       </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @room.image.url %>
</p>
<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.size %>
</p>

<p>
  <strong>Checkin:</strong>
  <%= @room.checkin %>
</p>

<p>
  <strong>Checkout:</strong>
  <%= @room.checkout %>
</p>

<p>
  <strong>Adults:</strong>
  <%= @room.adults %>
</p>

<p>
  <strong>Kids:</strong>
  <%= @room.kids %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.size %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @room.beds %>
</p>

<p>
  <strong>Accomodates:</strong>
  <%= @room.accomodates %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/shared/_footer.html.erb
<div class="row">
    <div class="col-lg-3">
        <p>SECURE PAYMENT</p>
    </div>
    <div class="col-lg-3">
        <p>TEL: +254 712 345 678</p>
        <p>E-MAIL: info@mysite.com</p>
    </div>
    <div class="col-lg-3">
        <p>&copy; 2023 by  LE Petit Nairubyst </p>
    </div>
    <div>
        <a class="social" href=""><i class="fa fa-facebook"></i></a>
        <a class="social" href=""><i class="fa fa-twitter"></i></a>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav>
    <a href="/">Home</a>
    <a href="/">About</a>
    <%= link_to 'The Rooms', rooms_path %>
    <a href="/">Gallery</a>
    <a href="/">Contact</a>
    <a href="/">Book Now</a>
</nav>

app/views/terms/index.html.erb
<h1>Terms#index</h1>
<p>Find me in app/views/terms/index.html.erb</p>